name: Sync to Gitee

on:
  push:
    branches: [ main, master ]  # 当 main 或 master 分支有更新时触发
  workflow_dispatch:            # 允许手动在 Actions 页面点击触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1  # 或者使用 Yikun/hub-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 【修改这里】把 git@github.com 改为 https://github.com
          source-repo: "https://github.com/BigBinLi/j-image.git"
          # 下面这行保持不变（Gitee 必须用 SSH）
          destination-repo: "git@gitee.com:simiyu/j-image.git"
