name: Sync to Gitee

on:
  push:
    branches: [ main, master ]  # 当 main 或 master 分支有更新时触发
  workflow_dispatch:            # 允许手动在 Actions 页面点击触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1  # 或者使用 Yikun/hub-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:${{ github.repository }}.git"
          destination-repo: "git@gitee.com:${{ secrets.GITEE_USER }}/${{ github.event.repository.name }}.git"
